### ISSUE TITLE
terminal cams don't switch to radar boosters

### ISSUE THREAD

**Issue by JohnMetroid** [Zaggy1024/LC_TwoRadarMaps#3] opened 2024-01-27 06:49 UTC
I tested this mod with a player and a radar booster.  The main cams work as expected (can switch between the player and the radar booster), but the terminal cams ("view monitor") will only view the player character despite saying "switching to [radar booster name]"

cams appear to be correctly separated otherwise, and no error is thrown in the log

**Comment by Zaggy1024** [comment] 2024-01-27 07:24
Does this happen 100% of the time? I can't reproduce it on 1.1.1, so it might be an interaction with another mod. If you could provide a mod pack and steps to reproduce the problem, hopefully I can look into it.

**Comment by JohnMetroid** [comment] 2024-01-27 09:10
apologies for the oversight, I also have EnhancedRadarBooster installed which may contribute.  I can try to check the rest later if that doesn't reproduce the issue

Thanks

**Comment by JohnMetroid** [comment] 2024-01-30 08:39
Sorry for the late response, but I figured out the issue:  It's an issue between TwoRadarMaps + GeneralImprovements.  The "switch" command will still work on your new 2nd monitor, but the GeneralImprovements fast switch (default "left" and "right" arrow keys) will fail to see Radar Boosters as a valid source on the new screen.

I'm not sure which mod is better-suited to handle this one, so I will also post the report on GeneralImprovements so they can be aware of the conflict

Thanks again!

**Comment by Zaggy1024** [comment] 2024-01-30 08:42
Ah, thanks for figuring that out. I've been bogged down with OpenBodyCams so I haven't gotten to looking at this. It may need a fix on my side still, I'll have to check it out.

**Comment by JohnMetroid** [comment] 2024-01-30 08:44
No worries, if you need more info when you get around to looking, feel free to let me know.

I've been following your OpenBodyCams progress as well.  You're doing amazing work.  Appreciate all the time you're putting in.

Cheers.

Edit: dropping the GI report link, in case that yields fruit before you've had a chance to look https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/issues/95

**Comment by Zaggy1024** [comment] 2024-01-30 22:25
This is fixed in https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/commit/7129ce27302724ba623f2c946e3c2f875c4e04ba

**Closed as completed by Zaggy1024** 2024-01-30 22:25 UTC
